apiVersion: v1
kind: Service
metadata:
  name: ohq-django-asgi
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: ohq-django-asgi
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ohq-django-asgi
  name: ohq-django-asgi
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ohq-django-asgi
  strategy:
    rollingUpdate:
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ohq-django-asgi
    spec:
      containers:
        - command:
            - /usr/local/bin/asgi-run
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: officehoursqueue.settings.production
            - name: DOMAIN
              value: ohq.io
            - name: GIT_SHA
              value: GITREKT
          image: pennlabs/office-hours-queue-backend:GITREKT
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ohq-django-asgi
spec:
  rules:
    - host: ohq.io
      http:
        paths:
          - backend:
              serviceName: ohq-django-asgi
              servicePort: 80
            path: /api/ws
  tls:
    - hosts:
        - ohq.io
      secretName: ohq-io-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ohq-io
spec:
  dnsNames:
    - ohq.io
    - "*.ohq.io"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: ohq-io-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ohq-django-wsgi
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: ohq-django-wsgi
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ohq-django-wsgi
  name: ohq-django-wsgi
spec:
  replicas: 4
  selector:
    matchLabels:
      name: ohq-django-wsgi
  strategy:
    rollingUpdate:
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ohq-django-wsgi
    spec:
      containers:
        - env:
            - name: DJANGO_SETTINGS_MODULE
              value: officehoursqueue.settings.production
            - name: DOMAIN
              value: ohq.io
            - name: GIT_SHA
              value: GITREKT
          image: pennlabs/office-hours-queue-backend:GITREKT
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ohq-django-wsgi
spec:
  rules:
    - host: ohq.io
      http:
        paths:
          - backend:
              serviceName: ohq-django-wsgi
              servicePort: 80
            path: /api
          - backend:
              serviceName: ohq-django-wsgi
              servicePort: 80
            path: /admin
          - backend:
              serviceName: ohq-django-wsgi
              servicePort: 80
            path: /assets
  tls:
    - hosts:
        - ohq.io
      secretName: ohq-io-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ohq-io
spec:
  dnsNames:
    - ohq.io
    - "*.ohq.io"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: ohq-io-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ohq-react
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: ohq-react
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ohq-react
  name: ohq-react
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ohq-react
  strategy:
    rollingUpdate:
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ohq-react
    spec:
      containers:
        - env:
            - name: DOMAIN
              value: ohq.io
            - name: PORT
              value: "80"
            - name: GIT_SHA
              value: GITREKT
          image: pennlabs/office-hours-queue-frontend:GITREKT
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ohq-react
spec:
  rules:
    - host: ohq.io
      http:
        paths:
          - backend:
              serviceName: ohq-react
              servicePort: 80
            path: /
  tls:
    - hosts:
        - ohq.io
      secretName: ohq-io-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ohq-io
spec:
  dnsNames:
    - ohq.io
    - "*.ohq.io"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: ohq-io-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ohq-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: ohq-redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ohq-redis
  name: ohq-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ohq-redis
  strategy:
    rollingUpdate:
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ohq-redis
    spec:
      containers:
        - env:
            - name: GIT_SHA
              value: GITREKT
          image: redis:6.0
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: ohq-celery
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: ohq-celery
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ohq-celery
  name: ohq-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ohq-celery
  strategy:
    rollingUpdate:
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ohq-celery
    spec:
      containers:
        - command:
            - celery
            - -A
            - officehoursqueue
            - worker
            - -lINFO
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: officehoursqueue.settings.production
            - name: DOMAIN
              value: ohq.io
            - name: GIT_SHA
              value: GITREKT
          image: pennlabs/office-hours-queue-backend:GITREKT
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ohq-celery
spec:
  rules:
    - host: ohq.io
      http:
        paths: []
  tls:
    - hosts:
        - ohq.io
      secretName: ohq-io-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ohq-io
spec:
  dnsNames:
    - ohq.io
    - "*.ohq.io"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: ohq-io-tls
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    name: ohq-calculate-waits
  name: ohq-calculate-waits
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - python
                - manage.py
                - calculatewaittimes
              env:
                - name: GIT_SHA
                  value: GITREKT
              envFrom:
                - secretRef:
                    name: office-hours-queue
              image: pennlabs/office-hours-queue-backend:GITREKT
              imagePullPolicy: IfNotPresent
              name: worker
          restartPolicy: Never
  schedule: lol * * * *
  successfulJobsHistoryLimit: 1
