apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
  name: Default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: Default
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
    name: mobile-django
  name: mobile-django
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mobile-django
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mobile-django
    spec:
      containers:
        - env:
            - name: DOMAINS
              value: studentlife.pennlabs.org,portal.pennmobile.org,pennmobile.org
            - name: DJANGO_SETTINGS_MODULE
              value: pennmobile.settings.production
            - name: GIT_SHA
              value: TESTSHA
          envFrom:
            - secretRef:
                name: penn-mobile
          image: pennlabs/penn-mobile-backend:TESTSHA
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
  name: Default
spec:
  rules:
    - host: studentlife.pennlabs.org
      http:
        paths:
          - backend:
              service:
                name: Default
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: portal.pennmobile.org
      http:
        paths:
          - backend:
              service:
                name: Default
                port:
                  number: 80
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: Default
                port:
                  number: 80
            path: /assets
            pathType: Prefix
    - host: pennmobile.org
      http:
        paths:
          - backend:
              service:
                name: Default
                port:
                  number: 80
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: Default
                port:
                  number: 80
            path: /assets
            pathType: Prefix
  tls:
    - hosts:
        - studentlife.pennlabs.org
      secretName: pennlabs-org-tls
    - hosts:
        - portal.pennmobile.org
      secretName: pennmobile-org-tls
    - hosts:
        - pennmobile.org
      secretName: pennmobile-org-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
  name: pennlabs-org
spec:
  dnsNames:
    - pennlabs.org
    - "*.pennlabs.org"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: pennlabs-org-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
  name: pennmobile-org
spec:
  dnsNames:
    - pennmobile.org
    - "*.pennmobile.org"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: pennmobile-org-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
  name: Default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: Default
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
    name: mobile-react
  name: mobile-react
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mobile-react
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mobile-react
    spec:
      containers:
        - env:
            - name: DOMAIN
              value: portal.pennmobile.org
            - name: PORT
              value: "80"
            - name: GIT_SHA
              value: TESTSHA
          image: pennlabs/penn-mobile-frontend:TESTSHA
          imagePullPolicy: IfNotPresent
          name: worker
          ports:
            - containerPort: 80
      volumes: []
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
  name: Default
spec:
  rules:
    - host: portal.pennmobile.org
      http:
        paths:
          - backend:
              service:
                name: Default
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - portal.pennmobile.org
      secretName: pennmobile-org-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
  name: pennmobile-org
spec:
  dnsNames:
    - pennmobile.org
    - "*.pennmobile.org"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wildcard-letsencrypt-prod
  secretName: pennmobile-org-tls
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/managed-by: kittyhawk
    app.kubernetes.io/part-of: mobile
    app.kubernetes.io/version: TESTSHA
    name: mobile-get-laundry-snapshots
  name: mobile-get-laundry-snapshots
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - python
                - manage.py
                - get_snapshot
              env:
                - name: DJANGO_SETTINGS_MODULE
                  value: pennmobile.settings.production
                - name: GIT_SHA
                  value: TESTSHA
              envFrom:
                - secretRef:
                    name: penn-mobile
              image: pennlabs/penn-mobile-backend:TESTSHA
              imagePullPolicy: IfNotPresent
              name: worker
          restartPolicy: Never
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
